# Default values for rook-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: rook
namespace: rook
pool:
  name: replicapool
storage:
  useAllNodes: true
  useAllDevices: false
  deviceFilter:
  metadataDevice:
  location:
  storeConfig:
    storeType: bluestore
    databaseSizeMB: 1024 # this value can be removed for environments with normal sized disks (100 GB or larger)
    journalSizeMB: 1024  # this value can be removed for environments with normal sized disks (20 GB or larger)
storageClass:
  name: rook-block
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  # fstype: ext4
